#include "lolevel.h"
#include "platform.h"
#include "core.h"

static long *nrflag = (long*)0x60E8;

#include "../../../generic/capt_seq.c"

void __attribute__((naked,noinline)) sub_FFD2C9B8_my(long p)
{
  asm volatile (
              "STMFD   SP!, {R4-R6,LR}\n"
              "LDR     R3, =0x72BAC\n"
              "LDR     R5, =0x60E4\n"
              "SUB     SP, SP, #4\n"
              "LDR     R1, =0xFFFFFFFF\n"
              "STR     R0, [R5]\n"
              "LDR     R0, [R3]\n"
              "BL      sub_FFC0FB48\n"
              "LDR     R3, =0x9CFE0\n"
              "LDR     R0, [R3,#0x74]\n"
              "BL      sub_FFC8ABE4\n"
              "BL      sub_FFD2C938\n"
             
              "LDR     R3, =0x60EC\n"
              "LDR     R0, [R3]\n"
              "BL      sub_FFC8B090\n"
            "BL      wait_until_remote_button_is_released\n"
              "BL      capt_seq_hook_set_nr\n"
              "B       sub_FFD2C9F4\n"
  );
}

void __attribute__((naked,noinline)) sub_FFD297A4_my(long p)
{
  asm volatile (
              "STMFD   SP!, {R4,LR}\n"
              "LDR     R4, [R0,#0xC]\n"
              "BL      sub_FFD32564\n"
              "CMP     R0, #0\n"
              "BNE     loc_FFD297BC\n"
              "BL      sub_FFD32570\n"
    "loc_FFD297BC:\n"
              "MOV     R0, #0xC\n"
              "BL      sub_FFD32584\n"
              "TST     R0, #1\n"
              "MOV     R2, R4\n"
              "MOV     R0, R4\n"
              "BEQ     loc_FFD297E4\n"
              "MOV     R0, #1\n"
              "MOV     R1, R0\n"
              "LDMFD   SP!, {R4,LR}\n"
              "B       sub_FFD27D20\n"
    "loc_FFD297E4:\n"
              "BL      sub_FFD2B80C\n"
              "TST     R0, #1\n"
              "MOV     R2, R4\n"
              "MOV     R1, #1\n"
              "BEQ     loc_FFD29800\n"
              "LDMFD   SP!, {R4,LR}\n"
              "B       sub_FFD27D20\n"
    "loc_FFD29800:\n"
              "BL      sub_FFD67F90\n"
              "BL      sub_FFC14714\n"
              "LDR     R2, =0x9CF24\n"
              "ADD     R3, R4, R4,LSL#1\n"
              "STR     R0, [R2,R3,LSL#5]\n"
              "MOV     R0, R4\n"
              "BL      sub_FFD2D120\n"
              "BL      sub_FFD2BD10\n"
              "BL      sub_FFD2BCAC\n"
              "MOV     R0, R4\n"

              "BL      sub_FFD2C9B8_my\n"
              "BL      capt_seq_hook_raw_here\n"

             // "BL      sub_FFD483A4\n"

              "MOV     R2, R4\n"
              "MOV     R1, #1\n"
              "BL      sub_FFD27D20\n"
              "LDMFD   SP!, {R4,LR}\n"
              "B       sub_FFD2CBAC\n"
  );
}

void __attribute__((naked,noinline)) capt_seq_task()    //IDA task_CaptSeqTask
{
  asm volatile (
          "STMFD   SP!, {R4,LR}\n"
          "SUB     SP, SP, #4\n"
          "MOV     R4, SP\n"
          "B       loc_FFD29CE4\n"
    "loc_FFD29B9C:\n"
          "LDR     R2, [SP,#0xC-0xC]\n"
          "LDR     R3, [R2]\n"
          "MOV     R0, R2\n"
          "CMP     R3, #0x14\n"
          "LDRLS   PC, [PC,R3,LSL#2]\n"
          "B       loc_FFD29CB8\n"
          ".long loc_FFD29C08\n"
          ".long loc_FFD29C14\n"
          ".long loc_FFD29C1C\n"
          ".long loc_FFD29C2C\n"
          ".long loc_FFD29C24\n"
          ".long loc_FFD29C34\n"
          ".long loc_FFD29C3C\n"
          ".long loc_FFD29C48\n"
          ".long loc_FFD29C50\n"
          ".long loc_FFD29C5C\n"
          ".long loc_FFD29C64\n"
          ".long loc_FFD29C6C\n"
          ".long loc_FFD29C74\n"
          ".long loc_FFD29C7C\n"
          ".long loc_FFD29C84\n"
          ".long loc_FFD29C90\n"
          ".long loc_FFD29C98\n"
          ".long loc_FFD29CA0\n"
          ".long loc_FFD29CA8\n"
          ".long loc_FFD29CB0\n"
          ".long loc_FFD29CCC\n"
    "loc_FFD29C08:\n"
          "BL      sub_FFD2B47C\n"
          "BL      shooting_expo_param_override\n"   // +
        //  "BL	 handle_is_off\n"
          "BL      sub_FFD278D0\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C14:\n"
     			//"BL      sub_FFD45048\n"
          "BL      sub_FFD297A4_my\n"
					"B       loc_FFD29CC8\n"
    "loc_FFD29C1C:\n"
          "BL      sub_FFD2B7FC\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C24:\n"
          "BL      sub_FFD2A6F4\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C2C:\n" //shooting but. rel.
          "BL      sub_FFD2AB10\n"
       //   "BL	 handle_is_on\n"            //+
          "B       loc_FFD29CC8\n"
    "loc_FFD29C34:\n"
          "BL      sub_FFD2AB20\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C3C:\n"
          "BL      sub_FFD2B548\n"
          "BL      sub_FFD278D0\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C48:\n"
          "BL      sub_FFD298B0\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C50:\n"
          "BL      sub_FFD2B5B0\n"
          "BL      sub_FFD278D0\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C5C:\n"
          "BL      sub_FFD2AB10\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C64:\n"
          "BL      sub_FFD2BD50\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C6C:\n"
          "BL      sub_FFD2C06C\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C74:\n"
          "BL      sub_FFD2C0F4\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C7C:\n"
          "BL      sub_FFD2C1BC\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C84:\n"
          "MOV     R0, #0\n"
          "BL      sub_FFD2C274\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C90:\n"
          "BL      sub_FFD2C3CC\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29C98:\n"
          "BL      sub_FFD2C464\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29CA0:\n"
          "BL      sub_FFD2C520\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29CA8:\n"
          "BL      sub_FFD2C608\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29CB0:\n"
          "BL      sub_FFD2C65C\n"
          "B       loc_FFD29CC8\n"
    "loc_FFD29CB8:\n"
          "MOV     R1, #0x330\n"
          "LDR     R0, =0xFFD29530\n"
          "ADD     R1, R1, #1\n"
          "BL      sub_FFC03AEC\n"
    "loc_FFD29CC8:\n"
          "LDR     R2, [SP,#0xC-0xC]\n"
    "loc_FFD29CCC:\n"
          "LDR     R3, =0x72B34\n"
          "LDR     R1, [R2,#4]\n"
          "LDR     R0, [R3]\n"
          "BL      sub_FFC0F9AC\n"
          "LDR     R0, [SP,#0xC-0xC]\n"
          "BL      sub_FFD295AC\n"
    "loc_FFD29CE4:\n"
          "LDR     R3, =0x72B38\n"
          "MOV     R1, R4\n"
          "LDR     R0, [R3]\n"
          "MOV     R2, #0\n"
          "BL      sub_FFC100C4\n"
          "TST     R0, #1\n"
          "BEQ     loc_FFD29B9C\n"
          "MOV     R1, #0x28C\n"
          "LDR     R0, =0xFFD2952C\n"
          "ADD     R1, R1, #3\n"
          "BL      sub_FFC03AEC\n"
          "BL      _ExitTask\n"
          "BL      sub_FFC11620\n"
          "ADD     SP, SP, #4\n"
          "LDMFD   SP!, {R4,PC}\n"
  );
}
